### ISSUE TITLE
最近把账号从weixin 转移到了wechat，结果就登陆不了了

### ISSUE THREAD

**Issue by moosetk** [scavin/docker-EFBv2#6]
因为腾讯强行要求在4月8日之前需要将账号转移到wechat（see https://www.sohu.com/a/488111465_404443 ）所以今天转移了一下并没有出现别的问题，除了efb用不了了，不知道是不是 web版的wechat的入口变了，不再是 https://login.weixin.qq.com/qrcode/****== ？显示目前账号无法使用此服务

**Comment by scavin** [comment]
wechat 无法使用 EFB WeChat Slave Channel，你可以试试隔壁 https://github.com/Tedrolin/efb-wechat-pc-slave

**Comment by moosetk** [comment]
tedrolin 大佬的总是连接失败 111 错误，不知道怎么回事。http://weixin.qq.com/*/*** 这种pc 的入口是没有问题的，所以大佬，你以后会不会把web 接口改成pc 接口呢？

**Comment by scavin** [comment]
不会修改。

**Comment by moosetk** [comment]
哦
